name: chat_ai_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  speech_to_text: ^5.3.1
  flutter_tts: ^3.3.0
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
